language: android
jdk: oraclejdk8
dist: trusty
sudo: required
group: edge

android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26

install:
  - sudo apt-get install build-essential
  - yes | sdkmanager 'ndk-bundle'
  - yes | sdkmanager 'cmake;3.6.4111459'

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

script:
  - ./gradlew build -x bintray connectedCheck --stacktrace